// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALNc3X_566XIiVcwBj39TGs40MHInB9Jg',
    appId: '1:554738028536:android:bff5040dcbc868f02f500d',
    messagingSenderId: '554738028536',
    projectId: 'prueba-cf251',
    storageBucket: 'prueba-cf251.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaEW8zgriwY_1jG_0hPUog7puw9bw0eKU',
    appId: '1:554738028536:ios:b63fa9a4d8300b462f500d',
    messagingSenderId: '554738028536',
    projectId: 'prueba-cf251',
    storageBucket: 'prueba-cf251.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXS6fgPHQ80j3vmYX7rfoFh5g9LhqTHOc',
    appId: '1:554738028536:web:e849b9ac3a1a33512f500d',
    messagingSenderId: '554738028536',
    projectId: 'prueba-cf251',
    authDomain: 'prueba-cf251.firebaseapp.com',
    storageBucket: 'prueba-cf251.firebasestorage.app',
  );
}
